// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LightningRisk.Services.LightningObservations.Weather
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WeatherGetResponse_data_records : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Time the observasation was issued by NEA</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Datetime { get; set; }
#nullable restore
#else
        public string Datetime { get; set; }
#endif
        /// <summary>A weather observation for the lightning</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records_item? Item { get; set; }
#nullable restore
#else
        public global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records_item Item { get; set; }
#endif
        /// <summary>Time of acquisition of data from NEA</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedTimestamp { get; set; }
#nullable restore
#else
        public string UpdatedTimestamp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records"/> and sets the default values.
        /// </summary>
        public WeatherGetResponse_data_records()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "datetime", n => { Datetime = n.GetStringValue(); } },
                { "item", n => { Item = n.GetObjectValue<global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records_item>(global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records_item.CreateFromDiscriminatorValue); } },
                { "updatedTimestamp", n => { UpdatedTimestamp = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("datetime", Datetime);
            writer.WriteObjectValue<global::LightningRisk.Services.LightningObservations.Weather.WeatherGetResponse_data_records_item>("item", Item);
            writer.WriteStringValue("updatedTimestamp", UpdatedTimestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
