services:
  lightningrisk.webapi:
    image: lightningrisk.webapi
    build:
      context: .
      dockerfile: LightningRisk.WebApi/Dockerfile
  lightningrisk.authorizer:
    image: lightningrisk.authorizer
    build:
      context: .
      dockerfile: LightningRisk.Authorizer/Dockerfile

