// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace LightningRisk.Services.WbgtObservations.Weather
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Weather400Error_errorMsg
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Invalid date format. Date format must be YYYY-MM-DD (2025-02-01) or YYYY-MM-DDTHH:mm:ss (2025-02-01T08:30:00).")]
        #pragma warning disable CS1591
        InvalidDateFormatDateFormatMustBeYYYYMMDD20250201OrYYYYMMDDTHHMmSs20250201T083000,
        #pragma warning restore CS1591
        [EnumMember(Value = "Invalid pagination token.")]
        #pragma warning disable CS1591
        InvalidPaginationToken,
        #pragma warning restore CS1591
    }
}
