// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace LightningRisk.Services.WbgtObservations.Weather
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Weather404Error : ApiException, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The code property</summary>
        public double? Code { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error_data? DataEscaped { get; set; }
#nullable restore
#else
        public global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error_data DataEscaped { get; set; }
#endif
        /// <summary>The errorMsg property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMsg { get; set; }
#nullable restore
#else
        public string ErrorMsg { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error"/> and sets the default values.
        /// </summary>
        public Weather404Error()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetDoubleValue(); } },
                { "data", n => { DataEscaped = n.GetObjectValue<global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error_data>(global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error_data.CreateFromDiscriminatorValue); } },
                { "errorMsg", n => { ErrorMsg = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("code", Code);
            writer.WriteObjectValue<global::LightningRisk.Services.WbgtObservations.Weather.Weather404Error_data>("data", DataEscaped);
            writer.WriteStringValue("errorMsg", ErrorMsg);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
