// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace LightningRisk.Services.WbgtObservations.Weather
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WeatherGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Token to retrieve next page if exists</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaginationToken { get; set; }
#nullable restore
#else
        public string PaginationToken { get; set; }
#endif
        /// <summary>The records property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data_records>? Records { get; set; }
#nullable restore
#else
        public List<global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data_records> Records { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data"/> and sets the default values.
        /// </summary>
        public WeatherGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "paginationToken", n => { PaginationToken = n.GetStringValue(); } },
                { "records", n => { Records = n.GetCollectionOfObjectValues<global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data_records>(global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data_records.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("paginationToken", PaginationToken);
            writer.WriteCollectionOfObjectValues<global::LightningRisk.Services.WbgtObservations.Weather.WeatherGetResponse_data_records>("records", Records);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
